from PyQt5 import QtCore
from PyQt5.QtCore import QSize, QRect, QCoreApplication, QMetaObject
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QWidget, QFrame, QPushButton, QLabel


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 768)
        MainWindow.setMinimumSize(QSize(1280, 768))
        MainWindow.setMaximumSize(QSize(1280, 768))
        self.centralwidget = QWidget(MainWindow)
        self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowCloseButtonHint)
        self.centralwidget.setObjectName(u"centralwidget")
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(-220, 120, 1691, 20))
        self.line.setLineWidth(4)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.Exit_but = QPushButton(self.centralwidget)
        self.Exit_but.setObjectName(u"Exit_but")
        self.Exit_but.setGeometry(QRect(1190, 690, 75, 71))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1030, 630, 151, 41))
        self.Timer = QLabel(self.centralwidget)
        self.Timer.setObjectName(u"Timer")
        self.Timer.setGeometry(QRect(1150, 630, 111, 41))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 60, 470, 13))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(-220, 280, 1691, 20))
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(-220, 440, 1691, 20))
        self.line_3.setLineWidth(4)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(-220, 600, 1691, 20))
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(1010, 610, 31, 171))
        self.line_5.setLineWidth(4)
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(250, 0, 16, 831))
        self.line_6.setLineWidth(4)
        self.line_6.setFrameShape(QFrame.VLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 670, 470, 51))
        font = QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(300, 670, 470, 51))
        self.label_4.setFont(font)
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(380, 0, 16, 831))
        self.line_7.setLineWidth(4)
        self.line_7.setFrameShape(QFrame.VLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(400, 650, 161, 91))
        self.label_5.setFont(font)
        self.line_8 = QFrame(self.centralwidget)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(520, 0, 16, 831))
        self.line_8.setLineWidth(4)
        self.line_8.setFrameShape(QFrame.VLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(550, 680, 121, 31))
        self.label_6.setFont(font)
        self.line_9 = QFrame(self.centralwidget)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(650, 0, 16, 831))
        self.line_9.setLineWidth(4)
        self.line_9.setFrameShape(QFrame.VLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(670, 682, 91, 21))
        self.label_7.setFont(font)
        self.line_10 = QFrame(self.centralwidget)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(770, 0, 16, 831))
        self.line_10.setLineWidth(4)
        self.line_10.setFrameShape(QFrame.VLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(790, 670, 211, 51))
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 210, 470, 13))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 370, 470, 13))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 540, 470, 13))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(270, 512, 111, 41))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(270, 360, 101, 41))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(270, 182, 111, 61))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(270, 42, 111, 41))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(400, 42, 121, 41))
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(400, 182, 121, 61))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(400, 350, 121, 61))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(400, 512, 121, 41))
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(540, 512, 111, 41))
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(540, 352, 111, 61))
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(540, 182, 101, 61))
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(536, 39, 111, 51))
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(670, 510, 111, 41))
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(670, 350, 111, 41))
        self.label_26 = QLabel(self.centralwidget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(670, 200, 111, 41))
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(670, 50, 111, 41))
        self.label_28 = QLabel(self.centralwidget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(790, 10, 471, 101))
        self.label_29 = QLabel(self.centralwidget)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(790, 160, 471, 101))
        self.label_30 = QLabel(self.centralwidget)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(790, 320, 471, 101))
        self.label_31 = QLabel(self.centralwidget)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(790, 490, 471, 101))
        self.label_32 = QLabel(self.centralwidget)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(1030, 690, 81, 16))
        self.label_33 = QLabel(self.centralwidget)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(1090, 690, 47, 13))
        self.label_34 = QLabel(self.centralwidget)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(1150, 690, 47, 13))
        self.Buy_Heal = QPushButton(self.centralwidget)
        self.Buy_Heal.setObjectName(u"Buy_Heal")
        self.Buy_Heal.setGeometry(QRect(1040, 720, 121, 31))
        self.Buy_4slot = QPushButton(self.centralwidget)
        self.Buy_4slot.setObjectName(u"Buy_4slot")
        self.Buy_4slot.setGeometry(QRect(1200, 580, 75, 23))
        self.Buy_3slot = QPushButton(self.centralwidget)
        self.Buy_3slot.setObjectName(u"Buy_3slot")
        self.Buy_3slot.setGeometry(QRect(1200, 420, 75, 23))
        self.Buy_2slot = QPushButton(self.centralwidget)
        self.Buy_2slot.setObjectName(u"Buy_2slot")
        self.Buy_2slot.setGeometry(QRect(1200, 260, 75, 23))
        self.Buy_1slot = QPushButton(self.centralwidget)
        self.Buy_1slot.setObjectName(u"Buy_1slot")
        self.Buy_1slot.setGeometry(QRect(1200, 100, 75, 23))
        self.label_35 = QLabel(self.centralwidget)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(1210, 542, 71, 31))
        self.label_36 = QLabel(self.centralwidget)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(1210, 382, 61, 31))
        self.label_37 = QLabel(self.centralwidget)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(1200, 230, 61, 31))
        self.label_38 = QLabel(self.centralwidget)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(1200, 70, 61, 31))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Exit_but.setText(QCoreApplication.translate("MainWindow", u"EXIT", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u0435 \u0447\u0435\u0440\u0435\u0437", None))
        self.Timer.setText(QCoreApplication.translate("MainWindow", u"TIMER", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0411\u0429\u0415\u0415 \u041d\u0410\u0417\u0412\u0410\u041d\u0418\u0415", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u0423\u0420\u041e\u041d", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u0421\u041a\u041e\u0420\u041e\u0421\u0422\u042c\n"
"\u0410\u0442\u0430\u043a\u0438", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0430\u0440\u043d\u043e\u0441\u0442\u044c", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0438\u0445\u0438\u044f", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0435\u043b\u0438\u0439", None))
        self.Buy_Heal.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0423\u041f\u0418\u0422\u042c \u0425\u0418\u041b\u041a\u0423", None))
        self.Buy_4slot.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0424\u041e\u0420\u041c\u0418\u0422\u042c", None))
        self.Buy_3slot.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0424\u041e\u0420\u041c\u0418\u0422\u042c", None))
        self.Buy_2slot.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0424\u041e\u0420\u041c\u0418\u0422\u042c", None))
        self.Buy_1slot.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0424\u041e\u0420\u041c\u0418\u0422\u042c", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"\u0426\u0415\u041d\u0410", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"\u0426\u0415\u041d\u0410", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"\u0426\u0415\u041d\u0410", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"\u0426\u0415\u041d\u0410", None))
    # retranslateUi

